backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Demo URL", name: "demoURL", widget: "string", required: false }
      - { label: "Repo URL", name: "repoURL", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "work"
    label: "Work Experience"
    folder: "src/content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Start Date", name: "dateStart", widget: "datetime" }
      - { label: "End Date", name: "dateEnd", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
